# Generated by Django 4.2.1 on 2023-07-19 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('user_phone', models.CharField(max_length=255)),
                ('user_mail', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=255)),
                ('admin_pass', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chuyenxe',
            fields=[
                ('chuyenxe_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('arrive_time', models.TimeField()),
                ('start_time', models.TimeField()),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ghe',
            fields=[
                ('ghe_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hang', models.IntegerField()),
                ('cot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nhanvienxe',
            fields=[
                ('nhanvien_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('bang_lai', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('job_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Xe',
            fields=[
                ('bien_so', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('hoatdong_time', models.DateField()),
                ('sanxuat_time', models.DateField()),
                ('phien_time', models.DateField()),
                ('row_number', models.IntegerField()),
                ('column_number', models.IntegerField()),
                ('madangkiem', models.CharField(max_length=255)),
                ('xe_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ve',
            fields=[
                ('ve_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('chuyenxe_id', models.ForeignKey(db_column='chuyenxe_id', on_delete=django.db.models.deletion.CASCADE, to='qlxk.chuyenxe')),
                ('ghe_id', models.ForeignKey(db_column='ghe_id', on_delete=django.db.models.deletion.CASCADE, to='qlxk.ghe')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_time', models.DateTimeField(auto_now_add=True)),
                ('user_action', models.CharField(max_length=255)),
                ('admin_id', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, to='qlxk.administrator')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ghe',
            name='bien_so',
            field=models.ForeignKey(db_column='Bien_so', on_delete=django.db.models.deletion.CASCADE, to='qlxk.xe'),
        ),
        migrations.CreateModel(
            name='Dieukhien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chuyenxe_id', models.ForeignKey(db_column='chuyenxe_id', on_delete=django.db.models.deletion.CASCADE, to='qlxk.chuyenxe')),
                ('nhanvien_id', models.ForeignKey(db_column='nhanvien_id', on_delete=django.db.models.deletion.CASCADE, to='qlxk.nhanvienxe')),
            ],
        ),
        migrations.CreateModel(
            name='Datve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ve_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ve_id', models.ForeignKey(db_column='ve_id', on_delete=django.db.models.deletion.CASCADE, to='qlxk.ve')),
            ],
        ),
        migrations.CreateModel(
            name='Danhgia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('rating', models.FloatField()),
                ('chuyenxe_id', models.ForeignKey(db_column='chuyenxe_id', on_delete=django.db.models.deletion.CASCADE, to='qlxk.chuyenxe')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chx_time', models.DateTimeField(auto_now_add=True)),
                ('chx_action', models.CharField(max_length=255)),
                ('admin_id', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, to='qlxk.administrator')),
                ('chuyenxe_id', models.ForeignKey(db_column='chuyenxe_id', on_delete=django.db.models.deletion.CASCADE, to='qlxk.chuyenxe')),
            ],
        ),
        migrations.AddField(
            model_name='chuyenxe',
            name='bien_so',
            field=models.ForeignKey(db_column='Bien_so', on_delete=django.db.models.deletion.CASCADE, to='qlxk.xe'),
        ),
    ]
