# Generated by Django 4.2.1 on 2023-07-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlxk', '0002_users_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ve',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
