# Generated by Django 4.2.1 on 2023-07-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlxk', '0003_alter_ve_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ve',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
