# Generated by Django 4.2.1 on 2023-07-20 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlxk', '0004_alter_ve_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chuyenxe',
            name='bien_so',
            field=models.ForeignKey(db_column='bien_so', on_delete=django.db.models.deletion.CASCADE, to='qlxk.xe'),
        ),
        migrations.AlterField(
            model_name='ghe',
            name='bien_so',
            field=models.ForeignKey(db_column='bien_so', on_delete=django.db.models.deletion.CASCADE, to='qlxk.xe'),
        ),
    ]
