# Generated by Django 4.2.1 on 2023-10-28 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlxk', '0006_rename_date_chuyenxe_chuyenxe_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ghe',
            old_name='cot',
            new_name='col',
        ),
        migrations.RenameField(
            model_name='ghe',
            old_name='hang',
            new_name='row',
        ),
    ]
