# Generated by Django 4.2.1 on 2023-10-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlxk', '0007_rename_cot_ghe_col_rename_hang_ghe_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='control',
            name='chuyenxe_id',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='Control',
        ),
        migrations.DeleteModel(
            name='Monitor',
        ),
    ]
