# Generated by Django 4.2.1 on 2023-10-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlxk', '0008_remove_control_admin_id_remove_control_chuyenxe_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xe',
            old_name='hoatdong_time',
            new_name='last_maintain',
        ),
        migrations.RenameField(
            model_name='xe',
            old_name='phien_time',
            new_name='production_date',
        ),
        migrations.RemoveField(
            model_name='nhanvienxe',
            name='bang_lai',
        ),
        migrations.RemoveField(
            model_name='nhanvienxe',
            name='job_time',
        ),
        migrations.RemoveField(
            model_name='xe',
            name='madangkiem',
        ),
        migrations.RemoveField(
            model_name='xe',
            name='sanxuat_time',
        ),
        migrations.AlterField(
            model_name='chuyenxe',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
